### ISSUE TITLE
我使用model_zoo里面的inceptionv4训练模型报错，使用的是GPU，不是Ascend,请问是 配置问题  还是 仅支持Ascend处理器？

### ISSUE THREAD

**Issue by gyr-kdgc** [mindspore-ai/mindspore#102]
[ERROR] KERNEL(31632,python):2021-01-07-01:05:33.108.293 [mindspore/ccsrc/backend/kernel_compiler/gpu/nn/fused_batch_norm_ex_gpu_kernel.h:127] Init] tensor shape is 2, FusedBatchNormExGpuKernel should be 4
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    inception_v4_train()
  File "train.py", line 153, in inception_v4_train
    model.train(config.epoch_size, train_dataset, callbacks=callbacks, dataset_sink_mode=False)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 592, in train
    sink_size=sink_size)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 385, in _train
    self._train_process(epoch, train_dataset, list_callback, cb_params)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 513, in _train_process
    outputs = self._train_network(*next_element)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 331, in __call__
    out = self.compile_and_run(*inputs)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 588, in compile_and_run
    self.compile(*inputs)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 575, in compile
    _executor.compile(self, *inputs, phase=self.phase, auto_parallel_mode=self._auto_parallel_mode)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/common/api.py", line 502, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore/ccsrc/backend/kernel_compiler/gpu/nn/fused_batch_norm_ex_gpu_kernel.h:127 Init] tensor shape is 2, FusedBatchNormExGpuKernel should be 4

**Comment by DouSong** [comment]
你好，当前该网络仅支持Ascend哈

**Comment by gyr-kdgc** [comment]
> 你好，当前该网络仅支持Ascend哈

那model_zoo中所有的网络都只支持Ascend吗？有没有可以支持GPU的算法

**Comment by leonwanghui** [comment]
@gyr-kdgc Sorry for the late replies, you can check out MindSpore network support matrix (https://www.mindspore.cn/doc/note/zh-CN/r1.1/network_list_ms.html) to see which models are supported by GPU.

**Comment by gyr-kdgc** [comment]
> Sorry for the late replie

ok，thank you~
