### ISSUE TITLE
在cpu上运行官方文档上的lenet demo分布式训练Parameter Server模式失败

### ISSUE THREAD

**Issue by zhangle-java** [mindspore-ai/mindspore#113]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
`/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: 1.1.0
- **Python version (e.g., Python 3.7.5)**: 3.7
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: windows 10

## Describe the current behavior
我从gitee上clone了mindspore项目，然后想根据 [官方文档](https://www.mindspore.cn/tutorial/training/zh-CN/r1.1/advanced_use/apply_parameter_server_training.html) 将lenet demo修改成Parameter Server模式失败了

## Describe the expected behavior
我可以正常运行起来

## Steps to reproduce the issue
1. 通过git clone 下载代码
2. 用pycharm打开 model_zoo/official/cv/lenet 目录
3.修改model_zoo/official/cv/lenet/train.py 文件
![image](https://user-images.githubusercontent.com/29698544/106983994-c35d4f80-67a1-11eb-9d97-1c1188df1321.png)
4.下载mnist训练数据
![image](https://user-images.githubusercontent.com/29698544/106984136-f6074800-67a1-11eb-90b5-e438ff0619ba.png)
5.运行代码，启动参数和环境变量如下
![image](https://user-images.githubusercontent.com/29698544/106984222-1e8f4200-67a2-11eb-9097-9d148d1b97f6.png)

## Related log / screenshot
D:\workspace\mindspore-test\venv\Scripts\python.exe D:/workspace/github/mindspore/model_zoo/official/cv/lenet/train.py --device_target=CPU --data_path=mnist_data --ckpt_path=checkpoint
============== Starting Training ==============
Traceback (most recent call last):
  File "D:/workspace/github/mindspore/model_zoo/official/cv/lenet/train.py", line 70, in <module>
    model.train(cfg['epoch_size'], ds_train, callbacks=[time_cb, ckpoint_cb, LossMonitor()], dataset_sink_mode=False)
  File "D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\train\model.py", line 592, in train
    sink_size=sink_size)
  File "D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\train\model.py", line 385, in _train
    self._train_process(epoch, train_dataset, list_callback, cb_params)
  File "D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\train\model.py", line 513, in _train_process
    outputs = self._train_network(*next_element)
  File "D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\cell.py", line 331, in __call__
    out = self.compile_and_run(*inputs)
  File "D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\cell.py", line 588, in compile_and_run
    self.compile(*inputs)
  File "D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\cell.py", line 575, in compile
    _executor.compile(self, *inputs, phase=self.phase, auto_parallel_mode=self._auto_parallel_mode)
  File "D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\common\api.py", line 502, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore\ccsrc\runtime\device\cpu\kernel_select_cpu.cc:299 SetKernelInfo] Operator[Push] is not support. Trace: 
In file D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\optim\momentum.py(36)/        success = F.depend(success, _ps_pull(_ps_push((learning_rate, gradient, momentum), shapes), weight))/
In file D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\optim\momentum.py(151)/            success = self.hyper_map(F.partial(_momentum_opt, self.opt, self.momentum, lr), gradients, params, moments,/
In file D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\wrap\cell_wrapper.py(251)/        return F.depend(loss, self.optimizer(grads))/

WARNING: Logging before InitGoogleLogging() is written to STDERR
[WARNING] KERNEL(17656,?):2021-2-5 10:12:20 [mindspore\ccsrc\backend\kernel_compiler\cpu\cpu_kernel_factory.cc:92] GetSupportedKernelAttrList] Not registered CPU kernel: op[Push]!
[ERROR] DEVICE(17656,?):2021-2-5 10:12:20 [mindspore\ccsrc\runtime\device\cpu\kernel_select_cpu.cc:299] SetKernelInfo] Operator[Push] is not support. Trace: 
In file D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\optim\momentum.py(36)/        success = F.depend(success, _ps_pull(_ps_push((learning_rate, gradient, momentum), shapes), weight))/
In file D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\optim\momentum.py(151)/            success = self.hyper_map(F.partial(_momentum_opt, self.opt, self.momentum, lr), gradients, params, moments,/
In file D:\workspace\mindspore-test\venv\lib\site-packages\mindspore\nn\wrap\cell_wrapper.py(251)/        return F.depend(loss, self.optimizer(grads))/

**Comment by yuyicg** [comment]
The support for CPU of parameter server training is still under development, at present, only GPU and Ascend devices are supported. It will be released in the subsequent version. Thank you for your feedback.
