### ISSUE TITLE
ops.UniformInt can't suppor larger tensor. 

### ISSUE THREAD

**Issue by zhz44** [mindspore-ai/mindspore#122]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
`/device gpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: 1.1.1
- **Python version (e.g., Python 3.7.5)**: 3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
- **GCC/Compiler version (if compiled from source)**: gcc 7.5.0

## Describe the current behavior

The following code will produce the error when the shape size is greater than (24, 24)
```
import mindspore
from mindspore import Tensor
from mindspore import context

context.set_context(mode=context.GRAPH_MODE, device_target="GPU")
randint = mindspore.ops.UniformInt()
minv = Tensor(0, mindspore.int32)
maxv = Tensor(5, mindspore.int32)
shape = (1024,1024)
rand_num = randint(shape, minv, maxv)
```

error message:
```
[ERROR] KERNEL(4285,python3.7):2021-02-23-14:27:45.053.085 [mindspore/ccsrc/backend/kernel_compiler/gpu/math/random_op_gpu_kernel.h:82] Launch] For UniformInt op, `minval` should be strictly less than `maxval`
[ERROR] DEVICE(4285,python3.7):2021-02-23-14:27:45.053.133 [mindspore/ccsrc/runtime/device/kernel_runtime.cc:946] LaunchKernelMod] Launch kernel failed.
```
## Describe the expected behavior

According to the API documents, the code above should return a tensor with given size.

## Steps to reproduce the issue
1. copy the code above into a text editor and save it
2. run it

## Related log / screenshot
```
[WARNING] ME(4404:140490942375744,MainProcess):2021-02-23-14:27:44.361.675 [mindspore/ops/operations/array_ops.py:2302] WARN_DEPRECATED: The usage of Pack is deprecated. Please use Stack.
[ERROR] KERNEL(4285,python3.7):2021-02-23-14:27:45.053.085 [mindspore/ccsrc/backend/kernel_compiler/gpu/math/random_op_gpu_kernel.h:82] Launch] For UniformInt op, `minval` should be strictly less than `maxval`
[ERROR] DEVICE(4285,python3.7):2021-02-23-14:27:45.053.133 [mindspore/ccsrc/runtime/device/kernel_runtime.cc:946] LaunchKernelMod] Launch kernel failed.
[ERROR] DEVICE(4285,python3.7):2021-02-23-14:27:45.053.148 [mindspore/ccsrc/runtime/device/kernel_runtime.cc:958] LaunchKernel] LaunchKernelMod failed!
[ERROR] SESSION(4285,python3.7):2021-02-23-14:27:45.053.164 [mindspore/ccsrc/backend/session/gpu_session.cc:306] Execute] GPU execute graph failed!
Traceback (most recent call last):
  File "randint.py", line 13, in <module>
    rand_num = randint(shape, minv, maxv)
  File "/home/.local/lib/python3.7/site-packages/mindspore/ops/primitive.py", line 186, in __call__
    return _run_op(self, self.name, args)
  File "/home/.local/lib/python3.7/site-packages/mindspore/common/api.py", line 75, in wrapper
    results = fn(*arg, **kwargs)
  File "/home/.local/lib/python3.7/site-packages/mindspore/ops/primitive.py", line 525, in _run_op
    output = real_run_op(obj, op_name, args)
RuntimeError: mindspore/ccsrc/backend/session/gpu_session.cc:306 Execute] GPU execute graph failed!
```

**Comment by cxl-ll** [comment]
Hello.the problem is being reproduced for verification,and the result will be informed to you as soon as possible.
