### ISSUE TITLE
mindspore gpu import error

### ISSUE THREAD

**Issue by Light--** [mindspore-ai/mindspore#133]
$ python
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mindspore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/data/pkgs/miniconda3/conda/envs/LPD/lib/python3.7/site-packages/mindspore/__init__.py", line 17, in <module>
    from ._check_version import check_version_and_env_config
  File "/home/data/pkgs/miniconda3/conda/envs/LPD/lib/python3.7/site-packages/mindspore/_check_version.py", line 384, in <module>
    check_version_and_env_config()
  File "/home/data/pkgs/miniconda3/conda/envs/LPD/lib/python3.7/site-packages/mindspore/_check_version.py", line 368, in check_version_and_env_config
    env_checker.check_env(e)
  File "/home/data/pkgs/miniconda3/conda/envs/LPD/lib/python3.7/site-packages/mindspore/_check_version.py", line 60, in check_env
    raise e
  File "/home/data/pkgs/miniconda3/conda/envs/LPD/lib/python3.7/site-packages/mindspore/_check_version.py", line 362, in check_version_and_env_config
    from . import _c_expression
ImportError: /home/data/pkgs/miniconda3/conda/envs/LPD/lib/python3.7/site-packages/mindspore/_c_expression.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudnnGetFilterSizeInBytes, version libcudnn.so.7

**Comment by VectorSL** [comment]
cudnnGetFilterSizeInBytes was definded in cudnn whose version is greater than 7.6.0. so check your cudnn version and update it.
