### ISSUE TITLE
ops.concat报错：Single op compile failed, op: trans_data_6466981671876507577_0

### ISSUE THREAD

**Issue by beauty-girl-cxy** [mindspore-ai/mindspore#223]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> `/device ascend`</br>

### Software Environment:
- **MindSpore version (source or binary)**: 1.9
- **Python version (e.g., Python 3.7.5)**:3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu18.04
- **GCC/Compiler version (if compiled from source)**: 9.4.0

## Describe the current behavior
ops.concat报错：
![b8f98ea5fe844306cbe8a7072283b2a](https://user-images.githubusercontent.com/55454389/208302973-2c08e5d5-2877-4311-8b8d-382c6fbbaacd.png)
详细问题：
```shell
Single op compile failed, op: trans_data_6466981671876507577_0
 except_msg: 2022-12-18 14:01:51.562909+00:00: Query except_msg:Traceback (most recent call last):
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/te_fusion/parallel_compilation.py", line 1621, in run
    op_impl_switch=self._op_impl_switch)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/te_fusion/fusion_manager.py", line 1292, in build_single_op
    compile_info = call_op()
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/te_fusion/fusion_manager.py", line 1279, in call_op
    opfunc(*inputs, *outputs, *new_attrs, **kwargs)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/utils/para_check.py", line 547, in _in_wrapper
    return func(*args, **kwargs)
  File "/usr/local/Ascend/nnae/latest/opp/op_impl/built-in/ai_core/tbe/impl/trans_data.py", line 192, in trans_data
    hwcn_2_fractal_z_g.hwcn_2_fractal_z_g(src, dst, src_format, dst_format, groups, kernel_name)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/utils/para_check.py", line 994, in in_wrapper
    return func(*args, **kwargs)
  File "/usr/local/Ascend/nnae/latest/opp/op_impl/built-in/ai_core/tbe/impl/hwcn_2_fractal_z_g.py", line 836, in hwcn_2_fractal_z_g
    instance.compute_c_le_16(tp)
  File "/usr/local/Ascend/nnae/latest/opp/op_impl/built-in/ai_core/tbe/impl/hwcn_2_fractal_z_g.py", line 675, in compute_c_le_16
    self._prepare_by_workspace(tp, self.ub_input, ub_offset, lk, lsn, is_tail)
  File "/usr/local/Ascend/nnae/latest/opp/op_impl/built-in/ai_core/tbe/impl/hwcn_2_fractal_z_g.py", line 467, in _prepare_by_workspace
    self._reorder_ws(tp, ub_input, is_tail)
  File "/usr/local/Ascend/nnae/latest/opp/op_impl/built-in/ai_core/tbe/impl/hwcn_2_fractal_z_g.py", line 436, in _reorder_ws
    tik_inst.vnchwconv(False, False, dst_addr_list, src_addr_list, repeat_cnt, dst_stride, src_stride)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_source_info.py", line 126, in wrapper
    f_return = func(*args, **kwargs)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_data_operation_api_.py", line 607, in vnchwconv
    vnchwconv_obj.run_all()
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_source_info.py", line 130, in wrapper
    f_return = func(*args, **kwargs)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_vector_api/tik_vector_fills_api_.py", line 447, in run_all
    self.vnchwconv_check_obj.check_all()
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_vector_api/tik_params_check_fills.py", line 750, in check_all
    self.check_list_vnchwconv()
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_vector_api/tik_params_check_fills.py", line 562, in check_list_vnchwconv
    check_address_align([src], ["src[" + str(src_idx) + "]"])
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/common/common_util.py", line 778, in check_address_align
    "Address align error, %s[%s] is not %s Byte align" % (name, tensor.offset, align_size))
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_check_util.py", line 610, in raise_error
    print_error_msg(msg, exception_type)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/tik/tik_lib/tik_check_util.py", line 279, in print_error_msg
    raise RuntimeError(dict_arg)
RuntimeError: {'errCode': 'EA0000', 'message': 'Address align error, src[1][6] is not 32 Byte align\nFile path: /usr/local/Ascend/nnae/6.0.RC1/opp/op_impl/built-in/ai_core/tbe/impl/hwcn_2_fractal_z_g.py, line 436\nThe context code cause the exception is:\n433                with tik_inst.else_scope():\n434                    src_stride = 1\n435                    dst_stride = 16\n436 ->             tik_inst.vnchwconv(False, False, dst_addr_list, src_addr_list, repeat_cnt, dst_stride, src_stride)\n437            with tik_inst.else_scope():\n438                if tp.src_n == 17:\n439                    return\n', 'traceback': 'Traceback:\n  File /usr/local/Ascend/nnae/6.0.RC1/opp/op_impl/built-in/ai_core/tbe/impl/hwcn_2_fractal_z_g.py, line 436, in _reorder_ws\n             tik_inst.vnchwconv(False, False, dst_addr_list, src_addr_list, repeat_cnt, dst_stride, src_stride)'}


----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/ascend/kernel/tbe/tbe_kernel_compile.cc:471 QueryProcess
  File "/root/workspace/mindspore_src_1.9/utils/wavelets.py", line 245, in afb1d
    h = ops.concat([h0, h1] * C, axis=0)
  File "/root/workspace/mindspore_src_1.9/utils/wavelets.py", line 335, in construct
    y = afb1d(lohi, h0_col, h1_col, mode=mode, dim=2)
  File "/root/workspace/mindspore_src_1.9/utils/wavelets.py", line 424, in construct
    ll, high = afb2d(ll, self.h0_col, self.h1_col, self.h0_row, self.h1_row, mode)
  File "/root/workspace/mindspore_src_1.9/main.py", line 111, in construct
    out_slice3,Yh_out=self.xfm(slice3)
  File "/root/workspace/mindspore_src_1.9/main.py", line 60, in construct
    xiaobo_inter = self.xiaobo_loss(groundtruth,interpolation_out)
  File "/root/workspace/mindspore_src_1.9/main.py", line 98, in construct
    loss, interpolation_out = self.network(input_volume, m_items, groundtruth_volume, groundtruth, train)
  File "/root/workspace/mindspore_src_1.9/main.py", line 166, in train
    loss, interpolation_out = model(input_volume, m_items, groundtruth_volume, groundtruth, True)
  File "/root/workspace/mindspore_src_1.9/main.py", line 292, in <module>
    train(args, model)
```

**Comment by cxl-ll** [comment]
Hello, the question is being analyzed and will be answered as soon as possible.
