### ISSUE TITLE
atlast300vpro安装mindspore2.1.1，run_check()报错

### ISSUE THREAD

**Issue by SoulProficiency** [mindspore-ai/mindspore#246]
已安装官网要求，安装最新版本的mindspore2.1.1，但是运行run_check()出现以下问题：
`
MindSpore version:  2.1.1
The result of multiplication calculation is correct, MindSpore has been installed on platform [Ascend] successfully!
[ERROR] KERNEL(40354,fffdd6e1f1e0,python):2023-10-13-09:30:47.546.313 [mindspore/ccsrc/kernel/oplib/op_info_utils.cc:172] LoadOpInfoJson] Get op info json suffix path failed, soc_version: Ascend310P3
[ERROR] KERNEL(40354,fffdd6e1f1e0,python):2023-10-13-09:30:47.546.421 [mindspore/ccsrc/kernel/oplib/op_info_utils.cc:111] GenerateOpInfos] Load op info json failed, version: Ascend310P3
`
同时运行mindyolo:
`python demo/predict.py --config ./configs/yolov5/yolov5s.yaml --weight ./yolov5s.ckpt --image_path ./bus.jpg `
爆出以下问题：
`2023-10-13 09:26:25,217 [WARNING] Parse Model, args: nearest, keep str type
2023-10-13 09:26:25,266 [WARNING] Parse Model, args: nearest, keep str type
2023-10-13 09:26:25,412 [INFO] number of network params, total: 7.254436M, trainable: 7.235389M
[ERROR] KERNEL(40106,fffd2d4e4340,python):2023-10-13-09:26:25.462.153 [mindspore/ccsrc/kernel/oplib/op_info_utils.cc:172] LoadOpInfoJson] Get op info json suffix path failed, soc_version: Ascend310P3
[ERROR] KERNEL(40106,fffd2d4e4340,python):2023-10-13-09:26:25.462.263 [mindspore/ccsrc/kernel/oplib/op_info_utils.cc:111] GenerateOpInfos] Load op info json failed, version: Ascend310P3
Traceback (most recent call last):
  File "demo/predict.py", line 333, in <module>
    infer(args)
  File "demo/predict.py", line 280, in infer
    checkpoint_path=args.weight,
  File "/home/mindyolo/mindyolo/mindyolo/models/model_factory.py", line 31, in create_model
    model = create_fn(**model_args, **kwargs)
  File "/home/mindyolo/mindyolo/mindyolo/models/yolov5.py", line 47, in yolov5
    model = YOLOv5(cfg=cfg, in_channels=in_channels, num_classes=num_classes, **kwargs)
  File "/home/mindyolo/mindyolo/mindyolo/models/yolov5.py", line 32, in __init__
    self.initialize_weights()
  File "/home/mindyolo/mindyolo/mindyolo/models/yolov5.py", line 41, in initialize_weights
    m.initialize_biases()
  File "/home/mindyolo/mindyolo/mindyolo/models/heads/yolov5_head.py", line 67, in initialize_biases
    for mi, s in zip(m.m, m.stride):  # from
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/common/tensor.py", line 456, in __getitem__
    out = tensor_operator_registry.get('__getitem__')(self, index)
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/ops/composite/multitype_ops/_compile_utils.py", line 183, in _tensor_getitem
    return data_update(tensor_update_types, tensor_update_args, self, new_index)
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/ops/composite/multitype_ops/_compile_utils.py", line 93, in data_update
    data = data_update_by_ops(transfer_type, arg, data, new_index, value)
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/ops/composite/multitype_ops/_compile_utils.py", line 125, in data_update_by_ops
    mask_index[0], mask_index[1], 0, 0, mask_index[2])
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/ops/composite/multitype_ops/_compile_utils.py", line 52, in strided_slice
    return strided_slice_(data, begin_strides, end_strides, step_strides)
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/ops/primitive.py", line 314, in __call__
    return _run_op(self, self.name, args)
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/ops/primitive.py", line 907, in _run_op
    stub = _pynative_executor.run_op_async(obj, op_name, args)
  File "/root/miniconda3/envs/ms2.1/lib/python3.7/site-packages/mindspore/common/api.py", line 1275, in run_op_async
    return self._executor.run_op_async(*args)
RuntimeError: Load op info form json config failed, version: Ascend310P3
C++ Call Stack: (For framework developers)
mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:431 Init
`
是mindspore和Ascend310P3不匹配吗？已按照官网要求的组件进行匹配的

**Comment by fuxiaoiii** [comment]
老哥我也是这个问题，同问

**Comment by SoulProficiency** [comment]
> 老哥我也是这个问题，同问

暂未有解决办法，目前租用modelarts，尝试在ascend910平台上进行自定义数据集的训练

**Comment by fuxiaoiii** [comment]
> ascend910平台上

老哥你是自定义镜像吗？

**Comment by fuxiaoiii** [comment]
> > 老哥我也是这个问题，同问
> 
> 暂未有解决办法，目前租用modelarts，尝试在ascend910平台上进行自定义数据集的训练

老哥你是自定义镜像吗？

**Comment by caiduoduo12138** [comment]
请问解决了吗？一样的问题，可以跑通官方的c++推理，但是运行mindspore出现问题

**Comment by caiduoduo12138** [comment]
请问解决了吗？一样的问题，可以跑通官方的c++推理，但是运行mindspore出现问题

**Comment by Ash-Lee233** [comment]
> 请问解决了吗？一样的问题，可以跑通官方的c++推理，但是运行mindspore出现问题

310机型不支持训练
