### ISSUE TITLE
No module named 'mindspore._c_expression' when trying to import Mindspore

### ISSUE THREAD

**Issue by some16** [mindspore-ai/mindspore#247]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> /device cpu

### Software Environment:
- **MindSpore version (source or binary)**: 1.5.2
- **Python version (e.g., Python 3.7.5)**: Python 3.7.17
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: MacOS Sonoma 14.0
- **GCC/Compiler version (if compiled from source)**: N/A

## Describe the current behavior
When attemping to import Mindspore this error occurs:
```ModuleNotFoundError: No module named 'mindspore._c_expression'```

## Describe the expected behavior
This error should not occur and Mindspore should import correctly

## Steps to reproduce the issue
1. Install Mindspore 1.5.2
2. Run ```python -c 'import mindspore'```

## Related log / screenshot
Full error:
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/.pyenv/versions/MTFN3.7.17/lib/python3.7/site-packages/mindspore/__init__.py", line 18, in <module>
    from . import common, train, log
  File "/Users/user/.pyenv/versions/MTFN3.7.17/lib/python3.7/site-packages/mindspore/common/__init__.py", line 16, in <module>
    from . import dtype
  File "/Users/user/.pyenv/versions/MTFN3.7.17/lib/python3.7/site-packages/mindspore/common/dtype.py", line 20, in <module>
    from .._c_expression import typing, EnvInstance_
ModuleNotFoundError: No module named 'mindspore._c_expression'
```

## Special notes for this issue
- I'm using pyenv, though as far as I know this shouldn't cause issue.
- I've seen issue #19, but this doesn't seem to be the same problem as far as I can tell.

**Comment by cxl-ll** [comment]
Hello, welcome to MindSpore. It is recommended that you try to install the latest version of MindSpore.
https://www.mindspore.cn/install

**Comment by 420xincheng** [comment]
### Environment
Name: mindspore
Version: 2.3.0rc4
Python 3.9.10 |
aarch64 GNU/Linux

### Error Log
```
from mindspore._c_expression import swap_cache
ImportError: cannot import name 'swap_cache' from 'mindspore._c_expression' (/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/_c_expression.cpython-39-aarch64-linux-gnu.so)
```
### Steps to reproduce the issue
When I use the following command：
```
bash ../scripts/msrun_launcher.sh \
"llama3/run_llama3.py \
--config /home/ma-user/work/run_llama3_8b_8k_800T_A2_64G_lora_dis_256.yaml \
--load_checkpoint /home/ma-user/work/llama3-8B.ckpt \
--auto_trans_ckpt False \
--use_parallel True \
--run_mode finetune \
--train_data /home/ma-user/work/train-fastchat256.mindrecord" 4
```

**Comment by 420xincheng** [comment]
### Environment
Name: mindspore
Version: 2.3.0rc4
Python 3.9.10 |
aarch64 GNU/Linux

### Error Log
```
from mindspore._c_expression import swap_cache
ImportError: cannot import name 'swap_cache' from 'mindspore._c_expression' (/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/_c_expression.cpython-39-aarch64-linux-gnu.so)
```
### Steps to reproduce the issue
When I use the following command：
```
bash ../scripts/msrun_launcher.sh \
"llama3/run_llama3.py \
--config /home/ma-user/work/run_llama3_8b_8k_800T_A2_64G_lora_dis_256.yaml \
--load_checkpoint /home/ma-user/work/llama3-8B.ckpt \
--auto_trans_ckpt False \
--use_parallel True \
--run_mode finetune \
--train_data /home/ma-user/work/train-fastchat256.mindrecord" 4
```
