### ISSUE TITLE
ModuleNotFoundError: No module named 'te'

### ISSUE THREAD

**Issue by songtianhui** [mindspore-ai/mindspore#259]
## Background
How to install the 'te' module

## Introduction
I have installed mindspore by command `pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/2.2.10/MindSpore/unified/x86_64/mindspore-2.2.10-cp39-cp39-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple`.
When I run `sh examples/pangu_draw_v3/run_sampling.sh` in mindone, it cannot import FlashAttention.

The traceback:
```
Traceback (most recent call last):
  File "/data/songtianhui.sth/projects/mindone/examples/pangu_draw_v3/pangu_sampling.py", line 7, in <module>
    from gm.helpers import SD_XL_BASE_RATIOS, VERSION2SPECS, create_model, init_sampling, load_img, perform_save_locally
  File "/data/songtianhui.sth/projects/mindone/examples/pangu_draw_v3/gm/helpers.py", line 12, in <module>
    from gm.modules.diffusionmodules.discretizer import Img2ImgDiscretizationWrapper, Txt2NoisyDiscretizationWrapper
  File "/data/songtianhui.sth/projects/mindone/examples/pangu_draw_v3/gm/modules/__init__.py", line 1, in <module>
    from .embedders.modules import GeneralConditioner
  File "/data/songtianhui.sth/projects/mindone/examples/pangu_draw_v3/gm/modules/embedders/__init__.py", line 1, in <module>
    from .modules import FrozenCLIPEmbedder, FrozenOpenCLIPEmbedder2, GeneralConditioner
  File "/data/songtianhui.sth/projects/mindone/examples/pangu_draw_v3/gm/modules/embedders/modules.py", line 6, in <module>
    from gm.modules.diffusionmodules.openaimodel import Timestep
  File "/data/songtianhui.sth/projects/mindone/examples/pangu_draw_v3/gm/modules/diffusionmodules/openaimodel.py", line 6, in <module>
    from gm.modules.attention import SpatialTransformer
  File "/data/songtianhui.sth/projects/mindone/examples/pangu_draw_v3/gm/modules/attention.py", line 13, in <module>
    from mindspore.nn.layer.flash_attention import FlashAttention
  File "/data/songtianhui.sth/apps/miniconda3/envs/pangu/lib/python3.9/site-packages/mindspore/nn/layer/flash_attention.py", line 24, in <module>
    from mindspore.ops._op_impl._custom_op.flash_attention.flash_attention_impl import get_flash_attention
  File "/data/songtianhui.sth/apps/miniconda3/envs/pangu/lib/python3.9/site-packages/mindspore/ops/_op_impl/_custom_op/__init__.py", line 17, in <module>
    from mindspore.ops._op_impl._custom_op.dsd_impl import dsd_matmul
  File "/data/songtianhui.sth/apps/miniconda3/envs/pangu/lib/python3.9/site-packages/mindspore/ops/_op_impl/_custom_op/dsd_impl.py", line 17, in <module>
    from te import tik
ModuleNotFoundError: No module named 'te'
```

**Comment by Ash-Lee233** [comment]
https://www.mindspore.cn/install
![image](https://github.com/mindspore-ai/mindspore/assets/49091981/407947e8-c2fc-4800-a284-4f8b07ea96a8)

**Comment by songtianhui** [comment]
> https://www.mindspore.cn/install ![image](https://private-user-images.githubusercontent.com/49091981/297647730-407947e8-c2fc-4800-a284-4f8b07ea96a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjUyNjgsIm5iZiI6MTcwNTU2NDk2OCwicGF0aCI6Ii80OTA5MTk4MS8yOTc2NDc3MzAtNDA3OTQ3ZTgtYzJmYy00ODAwLWEyODQtNGY4YjA3ZWE5NmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MDI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NDk3ZDU3Y2JkOTc3Yjg5ZTY4YWZmYjRlZmU2YzA4MTZmYmM2ZjY4MGViNmYwOWI0NTcwNDMzZDM2ZGI4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KWTyrokBxzmxtm7BbgVFnVqvem_hsQn0h9OH8mcOB1o)

所以是这个只能在Ascend机器上面运行是吗？

**Comment by songtianhui** [comment]
Been explained in https://github.com/mindspore-lab/mindone/issues/293
