### ISSUE TITLE
 RuntimeError: Unsupported op [Div]

### ISSUE THREAD

**Issue by liuky74** [mindspore-ai/mindspore#26]
我在尝试自定义loss的时候报了一个不支持操作符的错误，写了一个测试代码如下：
```
context.set_context(mode=context.PYNATIVE_MODE, device_target='GPU',enable_mem_reuse=False)
a = ms.Tensor(4)
b= ms.Tensor(2)
c = P.Div()(a,b)
```
会报如下错误：
```
[ERROR] ME(3296,python3):2020-04-07-16:47:45.756.448 [mindspore/ccsrc/device/gpu/kernel_info_setter.cc:102] SelectAkgKernel] Not find op[Div] in akg
[ERROR] ME(3296,python3):2020-04-07-16:47:45.756.524 [mindspore/ccsrc/device/gpu/kernel_info_setter.cc:80] SupportedTypeList] Unsupported op [Div]
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/home/liuky/HDD_1/soft/anaconda3/envs/py375/lib/python3.7/site-packages/mindspore/ops/primitive.py", line 141, in __call__
    output = _run_op(self, self.name, args)
  File "/home/liuky/HDD_1/soft/anaconda3/envs/py375/lib/python3.7/site-packages/mindspore/common/api.py", line 68, in wrapper
    results = fn(*arg, **kwargs)
  File "/home/liuky/HDD_1/soft/anaconda3/envs/py375/lib/python3.7/site-packages/mindspore/ops/primitive.py", line 332, in _run_op
    output = real_run_op(obj, op_name, tuple(op_inputs), tuple(op_mask))
RuntimeError: mindspore/ccsrc/device/gpu/kernel_info_setter.cc:80 SupportedTypeList] Unsupported op [Div]
```
请问是什么问题呢？

**Comment by leonwanghui** [comment]
Hi @liuky74 , as the error indicates, currently MindSpore with GPU backend doesn't support `Div` operator, you can take a look at [MindSpore operator matrix](https://www.mindspore.cn/docs/zh-CN/master/operator_list.html) to see what operators can be supported by GPU.
