### ISSUE TITLE
lack of output shape checking in mindspore.nn.Conv2d

### ISSUE THREAD

**Issue by PhyllisJi** [mindspore-ai/mindspore#288]
### Software Environment:
- **MindSpore version (source or binary)**: binary
- **Python version (e.g., Python 3.7.5)**: 3.9
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **GCC/Compiler version (if compiled from source)**: 

## Describe the current behavior

```
Traceback (most recent call last):
  File "/mnt/AA_MoCoDiff/BR_MoCoDiff/bugs/ms/BUG1_conv_dilation_output_size.py", line 15, in <module>
    print(p(x).shape)
  File "/root/miniconda3/envs/mocodiff/lib/python3.9/site-packages/mindspore/nn/cell.py", line 705, in __call__
    raise err
  File "/root/miniconda3/envs/mocodiff/lib/python3.9/site-packages/mindspore/nn/cell.py", line 702, in __call__
    _pynative_executor.end_graph(self, output, *args, **kwargs)
  File "/root/miniconda3/envs/mocodiff/lib/python3.9/site-packages/mindspore/common/api.py", line 1215, in end_graph
    self._executor.end_graph(obj, output, *args, *(kwargs.values()))
RuntimeError: The pointer[primitive_] is null.

----------------------------------------------------
- Framework Unexpected Exception Raised:
----------------------------------------------------
This exception is caused by framework's unexpected error. Please create an issue at https://gitee.com/mindspore/mindspore/issues to get help.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/cpu/kernel/mkldnn/mkl_cpu_kernel.cc:391 ExecutePrimitive
```

## Describe the expected behavior

Mindspore.nn.Conv2d checks the output shape in advance to avoid 0-dimensional output and the underlying crash

## Steps to reproduce the issue
```python
import numpy as np
import mindspore


mindspore.context.set_context(device_target='CPU')

# 關於Conv2d中dilation對輸出形狀的影響問題，torch中會報出Output size too small等信息，而ms對此不做控制，會直接計算出零或者負輸出，其中負輸出會導致底層報錯
p = mindspore.nn.Conv2d(in_channels=8, out_channels=8, kernel_size=(3, 3), stride=(1, 1), pad_mode="pad", padding=(1, 1, 1, 1), dilation=(1, 8), group=8, has_bias=True, data_format="NCHW")
# 1. 空輸出
x = mindspore.Tensor(np.random.randn(1, 8, 14, 14).astype(np.float32))
print(p(x).shape)

# # 2. 負輸出，底層報錯
x = mindspore.Tensor(np.random.randn(1, 8, 13, 13).astype(np.float32))
print(p(x).shape)

```

**Comment by VectorSL** [comment]
请问是哪个版本的ms ? 
当前2.4 的版本我尝试运行会校验shape。
`[mindspore/ccsrc/kernel/kernel.cc:625] Resize] Invalid shape:[const vector]{1, 8, 13, -1}, kernel name:Conv2D`
![image](https://github.com/user-attachments/assets/1ea22d32-668c-48da-8408-b969507e0657)

**Comment by PhyllisJi** [comment]
> 请问是哪个版本的ms ? 当前2.4 的版本我尝试运行会校验shape。 `[mindspore/ccsrc/kernel/kernel.cc:625] Resize] Invalid shape:[const vector]{1, 8, 13, -1}, kernel name:Conv2D` ![image](https://private-user-images.githubusercontent.com/16863563/365554145-1ea22d32-668c-48da-8408-b969507e0657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTA3OTgsIm5iZiI6MTcyNTk1MDQ5OCwicGF0aCI6Ii8xNjg2MzU2My8zNjU1NTQxNDUtMWVhMjJkMzItNjY4Yy00OGRhLTg0MDgtYjk2OTUwN2UwNjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA2NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3M2Q0ZjI2MDc0OWFiZjdmMDU0ZjY2NGQ4ZmNhNzZkZmI3MmJlMmY3NjJlMTE1MWJjZTJlNDEzY2VlNTRlZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZTlfKhucFmSod5vzv9gJ99hE4FYgrTh2ex_ahBA-C0)

MindSpore 2.2.14
