### ISSUE TITLE
在4090上安装失败 No module named 'mindspore._c_expression'

### ISSUE THREAD

**Issue by Ethereal-sakura** [mindspore-ai/mindspore#320]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device ascend`</br>
> `/device gpu`</br>
> `/device cpu`</br>

/device gpu

### Software Environment:
- **MindSpore version (source or binary):master（Nightly build)**:
- **Python version (e.g., Python 3.7.5):3.9.11**:
- **OS platform and distribution (e.g., Linux Ubuntu 16.04):ubuntu20.04**:
- **GCC/Compiler version (if compiled from source):9.4.0**: 

## Describe the current behavior
按照这个教程进行的安装https://www.mindspore.cn/install/#command，
CUDA本身是11.6，所以没进行cuda这一步，安装了cudnn
cudnn从官网下载cudnn-linux-x86_64-8.5.0.96_cuda11-archive.tar.xz
gcc也是自带的，所以没进行gcc安装这一步

## Describe the expected behavior
在验证的时候出错

## Steps to reproduce the issue
1. python -c "import mindspore;mindspore.set_context(device_target='GPU');mindspore.run_check()"
2. 
3.

## Related log / screenshot
![image](https://github.com/user-attachments/assets/c148ab8f-18b7-4feb-a239-4c5bcd94ae56)

**Comment by zhouyifeng888** [comment]
看这错误可能是有多个版本在环境里同时存在冲突了，Nightly 里面的是dev版本，包名是mindspore-dev，正式版是mindspore，所以安装其中一个前，先要手动把另一个卸载掉，也不能安装之后再卸载另一个，如果误操作两个都同时存在了，需要先把两个都卸载掉，然后再装那个你需要的，否则很可能会出错，上述错误就是个典型例子；
还有要注意，2.2.14是已发布的GPU正式版本，后续的2.3 2.4以及Nightly 里面的（没记错应该是已经2.5了），都是非正式版，可能有什么bug；且这几个非正式版可能需要设置一下环境变量：export CUDA_HOME=/cuda，CUDA_HOME的路径可以随便写一个，不设置的话可能无法运行；
如果是cuda环境搭建问题的话，其实建议可以先拉一个docker镜像直接运行，2.2.14的文档里有直接拉取cuda11.6的镜像运行的操作步骤，然后直接在里面装其它版本；
还有一点注意，4090显卡如果是cuda11.1的话，是没法跑起来的，11.6才行，有时候环境里有多个cuda版本，建议也可以排查一下

**Comment by zh9586** [comment]
@HelloEveryonehh 你好，你的问题解决了吗？我也出现了相同的问题。

**Comment by zh9586** [comment]
找到原因了！

错误信息：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/miniconda3/envs/mindspore_py39/lib/python3.9/site-packages/mindspore/__init__.py", line 18, in <module>
    from mindspore.run_check import run_check
  File "/home/miniconda3/envs/mindspore_py39/lib/python3.9/site-packages/mindspore/run_check/__init__.py", line 17, in <module>
    from ._check_version import check_version_and_env_config
  File "/home/miniconda3/envs/mindspore_py39/lib/python3.9/site-packages/mindspore/run_check/_check_version.py", line 29, in <module>
    from mindspore._c_expression import MSContext, ms_ctx_param
ModuleNotFoundError: No module named 'mindspore._c_expression'

原因：
    我用的mindspore2.5，使用pip install mindspore-dev -i https://pypi.tuna.tsinghua.edu.cn/simple命令进行安装，其默认下载的是mindspore_dev-2.5.0.dev20241208-cp39-none-any.whl文件进行安装。虽然我的系统是x86_64架构，但是库中仍有很多动态库均是arm架构，包括找不到的_c_expression。

解决方法：
    在https://pypi.tuna.tsinghua.edu.cn/simple/mindspore-dev/下手动下载mindspore_dev-2.5.0.dev20241201-cp39-cp39-manylinux1_x86_64.whl，激活虚拟环境后，使用pip install mindspore_dev-2.5.0.dev20241201-cp39-cp39-manylinux1_x86_64.whl离线安装后就正常了。
