### ISSUE TITLE
How should I prepare cifa10 dataset to run resent50_cifa10 example?

### ISSUE THREAD

**Issue by wangli1426** [mindspore-ai/mindspore#48]
I launched a container using image  `mindspore/mindspore-gpu:0.3.0-alpha`  and attempted to run the resnet50_cifa10 example.

According to the tutorial, the dataset should be organized as follows.
```
.  
├── cifar-10-batches-bin  # train dataset
└── cifar-10-verify-bin   # infer dataset
``` 

Please be specify about what data should the folder `cifar-10-batches-bin` and  `cifar-10-verify-bin` contain? 

I tried to put mindrecord and data_batch_* in cifar-10-batches-py into the `cifar-10-batches-bin` folder, respectively. But in either the case, the training process failed with error message `RuntimeError: Thread ID 140285735020288 Unexpected error. There is no valid data matching the dataset API Cifar10Dataset.Please check file path or dataset API validation first.`

**Comment by jonyguo** [comment]
1. If you are using mindspore/example/resnet50_cifar10 to verify, the Cifar10 training data can be used to train run directly. You do not need to convert the training data(cifar-10-batches-bin & cifar-10-verify-bin) to mindrecord format.
    1) The train dir should be like below:
    ```
    $ ls cifar-10-batches-bin/
    data_batch_1.bin  data_batch_2.bin  data_batch_3.bin  data_batch_4.bin  data_batch_5.bin
    ```
    The dir "cifar-10-batches-bin" is the input dataset path for training.
    The above is enough for example.

    2) The test/evalute dir should be like below:
    ```
    $ ls cifar-10-verify-bin/
    test_batch.bin
    ```
    The dir "cifar-10-verify-bin" is input dataset path for evalute.

2. If you need to convert cifar10(the data in python version) to mindrecord, you can use tool  mindspore/mindspore/mindrecord/tools/cifar10_to_mr.py. This tool first transforms the cifar10 to mindrecord(s), and then uses MindDataset to read mindrecord(s) for training. All these can be found in link https://www.mindspore.cn/tutorial/en/master/index.html.

**Comment by wangli1426** [comment]
Thanks for the help. Following your suggestion, I managed to launch the training job with command `python train.py --dataset_path=./data/cifar-10-batches-bin --device_target="GPU"
`

However, the training process raises the following error messages. Any suggestion?

docker: mindspore/mindspore-gpu:0.3.0-alpha
GPU: 1080Ti

```log
[WARNING] MD(3725,python):2020-06-23-14:19:57.399.007 [mindspore/ccsrc/dataset/engine/datasetops/device_queue_op.cc:201] RetryPushGPUData] Retry pushing data...
[ERROR] ME(3725,python):2020-06-23-14:19:58.178.393 [mindspore/ccsrc/kernel/akg/akgkernelbuild.cc:467] OpBuild] No ret got, failed to call function [compilewithjson], args:
(('{"attr":[{"name":"multiples","value":[1,1,7,7]}],"fusion_type":4,"id":0,"impl_path":"","input_desc":[[{"data_type":"float32","name":"x","shape":[32,2048,1,1],"tensor_name":"x_0_0"}]],"name":"Tile","op":"Tile_13748654081404448976","output_desc":[{"data_type":"float32","name":"output","shape":[32,2048,7,7],"tensor_name":"output_0"}],"platform":"AKG","process":"cuda"}',)).
[ERROR] ME(3725,python):2020-06-23-14:19:58.178.429 [mindspore/ccsrc/kernel/akg/akgkernelbuild.cc:504] BuildByJson] Akg build failed op[Tile], json:{"attr":[{"name":"multiples","value":[1,1,7,7]}],"fusion_type":4,"id":0,"impl_path":"","input_desc":[[{"data_type":"float32","name":"x","shape":[32,2048,1,1],"tensor_name":"x_0_0"}]],"name":"Tile","op":"Tile_13748654081404448976","output_desc":[{"data_type":"float32","name":"output","shape":[32,2048,7,7],"tensor_name":"output_0"}],"platform":"AKG","process":"cuda"}
[ERROR] ME(3725,python):2020-06-23-14:19:58.178.493 [mindspore/ccsrc/kernel/akg/gpu/akg_gpu_kernel_build.cc:34] AkgGpuKernelBuild] : The pointer[kernel_pack] is null.
Traceback (most recent call last):

  File "train.py", line 97, in <module>
    model.train(epoch_size, dataset, callbacks=cb)

  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 512, in train
    dataset_sink_mode=dataset_sink_mode)

  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 350, in _train
    self._train_dataset_sink_process(epoch, train_dataset, list_callback, cb_params)

  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 391, in _train_dataset_sink_process
    outputs = self._train_network(*inputs)

  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 178, in __call__
    out = self.compile_and_run(*inputs)

  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 355, in compile_and_run
    _executor.compile(self, *inputs, phase=self.phase, auto_parallel_mode=self._auto_parallel_mode)

  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/common/api.py", line 375, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)

RuntimeError: mindspore/ccsrc/kernel/akg/gpu/akg_gpu_kernel_build.cc:34 AkgGpuKernelBuild] : The pointer[kernel_pack] is null.

[WARNING] MD(3725,python):2020-06-23-14:20:02.408.168 [mindspore/ccsrc/dataset/engine/datasetops/device_queue_op.cc:201] RetryPushGPUData] Retry pushing data...
```

**Comment by VectorSL** [comment]
hi, this problem was coursed by the unsetted environment variable, try `export PATH=$PATH:/usr/local/cuda10.1/bin:$PATH` (Assuming your CUDA version is 10.1, and your CUDA path is /usr/local/).

**Comment by wangli1426** [comment]
Hi @VectorSL,

Thanks for the quick response. Yes, my CUDA version is 10.1, but I didn't find folder `/usr/local/cuda10.1/bin`. My `/usr/local/cuda10.1/` folder is like this:
```
ls /usr/local/cuda-10.1/
LICENSE      README       compat/      doc/         lib64/       targets/     version.txt  
```

I tries to add `/usr/local/cuda-10.1/lib64` into `LD_LIBRARY_PATH` and re-run `python train.py --dataset_path=./data/cifar-10-batches-bin --device_target="GPU"`. However, the same error was shown.

**Comment by jonyguo** [comment]
I think maybe you can reinstall your CUDA according the link: https://developer.nvidia.com/cuda-toolkit-archive.
And then have a retry.
