### ISSUE TITLE
Encounter error - ImportError: libmpi.so.40: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by moseswmwong** [mindspore-ai/mindspore#64]
Hi,

I followed the instruction at https://www.mindspore.cn/install to install Mindspore 0.6.0beta on a standalone PC equipped with nVidia GTX 1080 GPU, running ubuntu 18.04. All checkpoint passed successful except the last testing step on line 2 "from mindspore import Tensor", error message is

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andy/anaconda3/envs/mindspore0.6.0/lib/python3.7/site-packages/mindspore/__init__.py", line 17, in <module>
    from . import common, train
  File "/home/andy/anaconda3/envs/mindspore0.6.0/lib/python3.7/site-packages/mindspore/common/__init__.py", line 16, in <module>
    from . import dtype
  File "/home/andy/anaconda3/envs/mindspore0.6.0/lib/python3.7/site-packages/mindspore/common/dtype.py", line 20, in <module>
    from .._c_expression import typing, EnvInstance_
ImportError: libmpi.so.40: cannot open shared object file: No such file or directory
`
Ubuntu desktop version 18.04.6
Nvidia driver version: 435.21
CUDA: 10.1.243
cuDNN: 7.6.5
Using Anaconda
Python environment created is Python 3.7.5
OpenMPI: not installed
NCCL: not installed
MindSpore: 0.6.0beta (GPU CUDA 10.1; Ubuntu-x86; Python 3.7.5; install method is pip)

Thanks for help!

**Comment by yuyicg** [comment]
@moseswmwong Please make sure openmpi is installed correctly, and the strong dependency on mpi will be fixed in the next release.

**Comment by Krisloveless** [comment]
@moseswmwong Hi, Try to export LD_LIBRARY_PATH={path_to_lib_mpi}:$LD_LIBRARY_PATH, this might help
