### ISSUE TITLE
Overflow with large tensors

### ISSUE THREAD

**Issue by LyricZhao** [mindspore-ai/mindspore#68]
### Hardware Environment:
GPU: 8 x NVIDIA P100

### Software Environment:
- **MindSpore version**: 0.6.0
- **Python version**: Python 3.7.5
- **OS platform and distribution**: Linux Ubuntu 18.04

## Describe the current behavior
Hi, I'm working on a Molecular Dynamics simulation using MindSpore. The code works great with 16384 molecules, but fails with 32768 molecules (https://github.com/LyricZhao/MindSpore-MD/blob/overflow-bug/mindspore_multi_gpu.py#L15). So I'm wondering whether there're `size_t` and `int` misuses in MindSpore.

## Steps to reproduce the issue
- Download the code file https://github.com/LyricZhao/MindSpore-MD/blob/overflow-bug/mindspore_multi_gpu.py
- Change line 16 following the comments in line 15
- Run the single file with MPI like `mpirun -n 8 python mindspore_multi_gpu.py`

## Related log
```
[ERROR] PRE_ACT(63106,python):2020-08-16-07:12:46.639.224 [mindspore/ccsrc/utils/convert_utils_base.h:49] IntToSize] The int value(-2147483648) is less than 0.
Traceback (most recent call last):
  File "mindspore_multi_gpu.py", line 87, in <module>
    times = run(100)
  File "mindspore_multi_gpu.py", line 75, in run
    R = model.predict(R, Tensor(0))
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/train/model.py", line 713, in predict
    result = self._predict_network(*predict_data)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 227, in __call__
    out = self.compile_and_run(*inputs)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 449, in compile_and_run
    _executor.compile(self, *inputs, phase=self.phase, auto_parallel_mode=self._auto_parallel_mode)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 425, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore/ccsrc/utils/convert_utils_base.h:49 IntToSize] The int value(-2147483648) is less than 0.
```

**Comment by suteng** [comment]
Could you give the shape of each tensor ?  Looks like the shape size exceed the int32 limitation.

**Comment by LyricZhao** [comment]
> Could you give the shape of each tensor ? Looks like the shape size exceed the int32 limitation.

The shape of `dr` in https://github.com/LyricZhao/MindSpore-MD/blob/overflow-bug/mindspore_multi_gpu.py#L37 is `(1, 32768, 32768, 2)` (i.e. 2,147,483,648 > 2,147,483,647 (INT_MAX)).

I don't think that there should be a limit, the interface of cudnn or your operator implements are just using `size_t` for index. Using `int` for index is not very "modernized C++".

What's more, the error here says "IntToSize error", I'm wondering why couldn't we use `size_t` at the very beginning but there's a conversion?

**Comment by lrongzheni** [comment]
Yes, using int for index is not proper, we will fixed this problem in future version.

**Comment by leonwanghui** [comment]
Hi @lrongzheni, could u give some updates for this issue? Thanks!
