### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by choosewhatulike** [mindspore-ai/mindspore#87]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device ascend`</br>
> `/device gpu`</br>

`/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: MindSpore-0.5.0
- **Python version (e.g., Python 3.7.5)**:  Python 3.7.9
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **GCC/Compiler version (if compiled from source)**: -

## Describe the current behavior
import mindspore 报错

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/remote-home/yfshao/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore/__init__.py", line 17, in <module>
    from . import common, train
  File "/remote-home/yfshao/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore/common/__init__.py", line 16, in <module>
    from . import dtype
  File "/remote-home/yfshao/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore/common/dtype.py", line 20, in <module>
    from .._c_expression import typing, EnvInstance_
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /remote-home/yfshao/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore/_c_expression.cpython-37m-x86_64-linux-gnu.so)

**Comment by choosewhatulike** [comment]
升级到mindspore-1.0 CPU版之后：
import mindspore

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/remote-home/yfshao/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore/__init__.py", line 18, in <module>
    from . import common, train
  File "/remote-home/yfshao/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore/common/__init__.py", line 16, in <module>
    from . import dtype
  File "/remote-home/yfshao/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore/common/dtype.py", line 20, in <module>
    from .._c_expression import typing, EnvInstance_
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by 1071034024** [comment]
感谢你使用MindSpore
第一个问题：Ubuntu16.04的环境上需要源码编译出whl安装包，再进行pip安装（直接安装的whl包是基于Ubuntu18.04的）
第二个问题：检查一下环境上是否安装了OpenSSL或者检查OpenSSL的版本，然后安装或者升级版本。

**Comment by choosewhatulike** [comment]
> 第一个问题：Ubuntu16.04的环境上需要源码编译出whl安装包，再进行pip安装（直接安装的whl包是基于Ubuntu18.04的）

通过编译源码解决，需要把 https://www.mindspore.cn/install 编译过程中的 `ascend` 换成 `cpu`.
