### ISSUE TITLE
 mindspore-ascend0.5中运行官方线性回归例子的时候出现profiling is not set的错误 

### ISSUE THREAD

**Issue by jxfruit** [mindspore-ai/mindspore#88]
| name       | about	                             | labels   |
| ---------- | ------------------------------------- | -------- |
| Bug Report | Use this template for reporting a bug | kind/bug |

## Environment
- **Hardware Environment(`Ascend`/`GPU`/`CPU`)**: 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /device ascend

- **Software Environment**:
-- MindSpore version (source or binary):0.5
-- Python version (e.g., Python 3.7.5):3.7.5
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
-- GCC/Compiler version (if compiled from source): 7.3

## Steps to reproduce the issue
1. 来源：官方GitHub中tutorials下面的linear_regression.py这个脚本
2. 在atlas800 9000（驱动版本：1.73.1005.1.B050）上执行该脚本出现下面的错误
Traceback (most recent call last):
  File "ln.py", line 51, in <module>
    model.train(1, ds_train, callbacks=LossMonitor(), dataset_sink_mode=False)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 535, in train
    dataset_sink_mode=dataset_sink_mode)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 357, in _train
    self._train_process(epoch, train_dataset, list_callback, cb_params)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 454, in _train_process
    for next_element in dataset_helper:
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/dataset_helper.py", line 193, in __next__
    if self.ind >= self.loop_count:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
有时候还会出现RuntimeError：THread ID 2814.... Unexpected error。 Profiling dir is not set.
然而我并没有开启profiling，官方给的例子怎么也跑不通，求大佬指点究竟是啥情况，感谢
3.

## Special notes for this issue

**Comment by jonyguo** [comment]
Hi 你好，
你用的应该是 mindspore 0.5 版本，但是linear_regression.py是在docs仓中的 master分支上，这两个版本是不匹配的，我试下了，docs仓0.5分支没有 linear_regression.py 这个文件，你可以试试其他的tutorials示例。
另，我们目前版本是这样的：
mindspore仓，mindinsight仓，mindarmour仓，docs仓 等涉及版本的，都是配套的，如果minspore是用r0.5，那使用其他仓里的内容时，也需要切换至r0.5分支上。
